CREATE TABLE PEGAWAI (
        ID INTEGER NOT NULL,
	NAME VARCHAR(50),
        PRIMARY KEY (ID)
);


INSERT INTO PEGAWAI VALUES (1021, 'Ardian');
INSERT INTO PEGAWAI  VALUES (1022, 'Mamad');
INSERT INTO PEGAWAI  VALUES (1011, 'Danang');
INSERT INTO PEGAWAI VALUES (1012, 'Divo');
INSERT INTO PEGAWAI  VALUES (1031, 'Parto');
INSERT INTO PEGAWAI  VALUES (1032, 'Anthony');
INSERT INTO PEGAWAI VALUES (1013, 'Christian');
INSERT INTO PEGAWAI  VALUES (1023, 'Jusi');
INSERT INTO PEGAWAI  VALUES (1033, 'Habib');

